project:
  type: website
  output-dir: docs
  resources:
    - "scripts/"
  render:
    - "index.qmd"
    - "pages/*.qmd"
  
website:
  title: "Small Area Estimation for Urban Analytics"
  favicon: assets/favicon.svg
  page-navigation: true
  navbar:
    background: "#1f4e5f"
    foreground: "#ffffff"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Tutorial"
        menu:
          - text: "I. Preparation"
          - text: "1. Overview"
            href: pages/prepare-inputs.qmd
          - text: "2. Example"
            href: pages/tutorial-dataprep.qmd
          - text: "II. Estimation"
          - text: "1. Direct estimation"
            href: pages/direct-estimation.qmd
          - text: "2. Area-level estimation"
            href: pages/bayesian-area-sae.qmd
          - text: "3. Reporting and visualisation"
            href: pages/reporting.qmd
          - text: "III. Extended Topics"
          - text: "1. Frequentist approaches to SAE"
            href: pages/frequentist-sae.qmd
          - text: "2. Unit-level estimation and MRP"
            href: pages/unit-level-sae.qmd
      - text: "Resources"
        menu:
          - text: "SAE Toolkit"
            href: pages/sae-toolkit.qmd
          - text: "FAQs"
            href: pages/faqs.qmd
      - text: "About"
        href: pages/about.qmd


  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Home"
        contents:
          - index.qmd
      - section: "Tutorial"
        contents:
          - section: "I. Preparation"
            contents:
              - pages/prepare-inputs.qmd
              - pages/tutorial-dataprep.qmd
          - section: "II. Estimation"
            contents:
              - pages/direct-estimation.qmd
              - pages/bayesian-area-sae.qmd
              - pages/reporting.qmd
          - section: "III. Extended Topics"
            contents:
              - pages/frequentist-sae.qmd
              - pages/unit-level-sae.qmd
      - section: "Resources"
        contents:
          - pages/sae-toolkit.qmd
          - pages/faqs.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    df-print: kable
    toc: true
    toc-depth: 3
    number-sections: true
    code-copy: true
    code-fold: true
    code-overflow: wrap
    link-external-newwindow: true
    fig-cap-location: bottom

execute:
  eval: true
  warning: false
  message: false
  freeze: false

editor:
  render-on-save: false
